apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: whoami
spec:
  version: {{ .TagName }}
  homepage: https://github.com/rajatjindal/kubectl-whoami
  platforms:
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    {{addURIAndSha "https://github.com/rajatjindal/kubectl-whoami/releases/download/{{ .TagName }}/kubectl-whoami_{{ .TagName }}_darwin_amd64.tar.gz" .TagName }}
    files:
    - from: "*"
      to: "."
    bin: kubectl-whoami
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    {{addURIAndSha "https://github.com/rajatjindal/kubectl-whoami/releases/download/{{ .TagName }}/kubectl-whoami_{{ .TagName }}_linux_amd64.tar.gz" .TagName }}
    files:
    - from: "*"
      to: "."
    bin: kubectl-whoami
  shortDescription: Show the subject that's currently authenticated as.
  caveats: |
    This plugin has only been tested with RBAC token, ServiceAccount token, and BasicAuth. 
    
    It will be great if we can get volunteers to test it with other Auth providers.
    
    Read the documentation at:
      https://github.com/rajatjindal/kubectl-whoami
  description: |
    This plugin show the subject that's currently authenticated as.

